config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "coaches#index"
  resources :bookings
  resources :coaches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :coach
end

app/models/coach.rb
class Coach < ApplicationRecord
    # before_action :authenticate_user!
    belongs_to :user
    has_one_attached :image
    has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :coaches
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @coach_id = params["coach_id"]
    @coach = Coach.find(params["coach_id"])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:date, :message, :coach_id)
    end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  # before_action :set_coach, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
    @coach = Coach.find(params[:id])
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)
    @coach.user = current_user

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    def set_user_coach
      id = params[:id]
      @coach = current_user.coaches.find_by_id(id)
  
      if @coach == nil
          redirect_to coaches_path
      end
  end
    # Only allow a list of trusted parameters through.
    def coach_params
      params.require(:coach).permit(:first_name, :last_name, :bio, :location, :session, :cost, :availability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%# <% raise %> 
  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>
  <%= form.hidden_field :coach_id, value: "#{@coach_id}" %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.date %></td>
        <td><%= booking.message %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= @coach.first_name %>
<%= @coach.last_name %>

<%= render 'form', {booking: @booking, coach_id: @coach_id} %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @booking.date %>
</p>


<p>
  <strong>Message:</strong>
  <%= @booking.message %>
</p>
</div>
<%# <%= link_to "BOOK_NOW" , new_booking_path(coach_id: @coach.id),class:"continue" %> %>
</div>
<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/coaches/_form.html.erb
<%= form_with(model: coach, local: true) do |form| %>
  <% if coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
        <% coach.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <% if coach.image.attached? %>
    <% coach.images.each do |img| %>
      <%= image_tag img %> 
      <% end %>
<% end%>
  
  

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :session %>
    <%= form.number_field :session %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.datetime_select :availability %>
  </div>

  <div class="field">
    <%# <%= form.label :image accept:'image/png, image/gif, image/jpeg, image/jpg' %> 
    <%= form.file_field :image, multiple: true %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<br>  
<% end %>

app/views/coaches/edit.html.erb
<h1>Edit Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Coaches</h1><br>
<% if user_signed_in? %>
<%= link_to 'Register New Coach', new_coach_path %><% end %>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Bio</th>
      <th>Location</th>
      <th>Session</th>
      <th>Cost</th>
      <th>Availability</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.first_name %></td>
        <td><%= coach.last_name %></td>
        <td><%= coach.bio %></td>
        <td><%= coach.location %></td>
        <td><%= coach.session %></td>
        <td><%= coach.cost %></td>
        <td><%= coach.availability %></td>
        <%# <td><%= image_tag coach_image_url(coach) %>
        <td><%= link_to 'View', coach_path(coach) %></td>

        <td><% if user_signed_in? && coach.user_id == current_user.id %></td>
        <%# <td><%= link_to 'Show', coach %>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
    <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<% if @coach.image.attached? %>
    <% @coach.images.each do |img| %>
      <%= image_tag img %>
    <% end  %>
<% end %> 

<p>
  <strong>First name:</strong>
  <%= @coach.first_name %><br>
</p>

<p>
  <strong>Last name:</strong>
  <%= @coach.last_name %><br>
</p>

<p>
  <strong>Bio:</strong>
  <%= @coach.bio %><br>
</p>

<p>
  <strong>Location:</strong>
  <%= @coach.location %><br>
</p>

<p>
  <strong>Session:</strong>
  <%= @coach.session %><br>
</p>

<p>
  <strong>Cost:</strong>
  <%= @coach.cost %><br>
</p>

<p>
  <strong>Availability:</strong>
  <%= @coach.availability %><br>
</p>




<%# <% if user_signed_in? && current.user_id != @coach.user_id %> 
<%# <%= button_to "Add #{@coach.first_name} to bookings" %> 
<%# <% unless user_signed_in? && current.user_id = @coach.user_id %> 
<%# <%= button_to "Add #{@coach.first_name} to bookings", new_user_session_path %> 
<%# <% end %> 
<%# <% end %> 



<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>

<%= link_to "BOOK_NOW" , new_booking_path(coach_id: @coach.id),class:"continue" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballers Alliance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
<%# <nav class="navbar navbar-light" style="background-color: #e3f2fd;"> %>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
   <div class="container">
    <a class="logo" href="/coaches">Ballers Alliance</a><br>
    <a class="navbar-brand" href="/coaches/new">Register As Coach </a>
    <a class="navbar-brand" href="/users/sign_in">Log in</a>
    <a class="navbar-brand" href="/users/sign_up">Sign up</a>
    <% if user_signed_in? %>
    <a class="navbar-brand" href="/bookings">My Bookings</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        </li>
      </ul>
    </div>
  </div>
</nav>
  <%# <%= render 'layouts/alerts' %> 
  <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
   <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %> 
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
 <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<div class="container">
  <%= yield %>
</div>
<footer class="footer footer-expand-xlarge footer-dark bg-dark fixed-bottom">
    <div class="container">
      Copyright &copy; Ballers Alliance 2020
    </div>
  </footer>
  </body>
</html>












  